### ISSUE TITLE
Calling the same page leads to errors

### ISSUE THREAD

**Issue by florian262000** [DNX-Development/WikiRace-Issues#2]
**Describe the bug**
As soon as a page is called in a game multiple times by a player, errors occur.

**To Reproduce**
E.g.: Start by "Computer", goto "Mikrocomputer", goto "Computer"

**Expected behavior**
Add article normal as visited page without errors

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Lobby Language: DE
 - WikiRace Version: 6f15e77

**Comment by Deeonix** [comment]
Can't reproduce anymore, closed due to inactivity

**Comment by Deeonix** [comment]
Reporting for another user, not tested yet. Container crashed after error.

**Log from 12.10.2021 21:49 CEST**
```
GAME START BROADCAST
SERVICE MANAGER: DE
Multivan_
SERVICE MANAGER: DE
VW-Bus
SERVICE MANAGER: DE
VW-Bus
System.ArgumentException: An item with the same key has already been added. Key: VW-Bus
at WikiRace.Services.WikiService.FetchWikiPage(String title)
```

**To Reproduce**
https://www.twitch.tv/videos/1174826851?t=01h46m13s
Steps to reproduce the behavior:
1. Start a time-based multiplayer game (with 2 players) on german wikipedia from "Multivan_" to "Zebrastreifen".
2. Click on 'VW-Bus' Link
3. Nothing happens

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - WikiRace Version: 2871db0

**Comment by Deeonix** [comment]
Reproduced: Click with two players at the same time on the 'VW-Bus' Link
